/**
 * seedData.ts
 * ===========
 * Data seed dari jurnal — 21 record bersih dengan 13 fitur.
 * Untuk di-import ke Firestore via Admin dashboard.
 */

import { PatientData } from './firestore';

export const SEED_PATIENTS: Omit<PatientData, 'id' | 'createdAt' | 'createdBy'>[] = [
  { nama: 'Pasien 01', umur: 25, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'ODHA', alasan_kunjungan: 'Konseling', riwayat_tes_hiv: 'Pernah (positif)', riwayat_ims: 'Pernah', jumlah_pasangan_seksual: 3, penggunaan_kondom: 'Tidak', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Belum Kawin', usia_pertama_hubungan: 19, terapi_arv: 'Ya', gejala_klinis: 'Gejala ringan', status_odhiv: 'ODHIV' },
  { nama: 'Pasien 02', umur: 30, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'ODHA', alasan_kunjungan: 'IMS', riwayat_tes_hiv: 'Pernah (positif)', riwayat_ims: 'Sedang terjadi', jumlah_pasangan_seksual: 5, penggunaan_kondom: 'Tidak', penggunaan_napza_suntik: 'Ya', status_pernikahan: 'Belum Kawin', usia_pertama_hubungan: 17, terapi_arv: 'Tidak', gejala_klinis: 'Gejala sedang', status_odhiv: 'ODHIV' },
  { nama: 'Pasien 03', umur: 28, jenis_kelamin: 'Perempuan', kelompok_populasi: 'Umum', alasan_kunjungan: 'Tes sukarela', riwayat_tes_hiv: 'Belum pernah', riwayat_ims: 'Tidak ada', jumlah_pasangan_seksual: 1, penggunaan_kondom: 'Ya', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Kawin', usia_pertama_hubungan: 22, terapi_arv: 'Tidak', gejala_klinis: 'Tidak ada gejala', status_odhiv: 'Bukan ODHIV' },
  { nama: 'Pasien 04', umur: 35, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'Umum', alasan_kunjungan: 'Rujukan klinis', riwayat_tes_hiv: 'Belum pernah', riwayat_ims: 'Tidak ada', jumlah_pasangan_seksual: 1, penggunaan_kondom: 'Ya', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Kawin', usia_pertama_hubungan: 25, terapi_arv: 'Tidak', gejala_klinis: 'Tidak ada gejala', status_odhiv: 'Bukan ODHIV' },
  { nama: 'Pasien 05', umur: 22, jenis_kelamin: 'Perempuan', kelompok_populasi: 'Umum', alasan_kunjungan: 'Konseling', riwayat_tes_hiv: 'Belum pernah', riwayat_ims: 'Tidak ada', jumlah_pasangan_seksual: 1, penggunaan_kondom: 'Ya', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Belum Kawin', usia_pertama_hubungan: 20, terapi_arv: 'Tidak', gejala_klinis: 'Tidak ada gejala', status_odhiv: 'Bukan ODHIV' },
  { nama: 'Pasien 06', umur: 40, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'Waria', alasan_kunjungan: 'Kontak serumah', riwayat_tes_hiv: 'Pernah (negatif)', riwayat_ims: 'Pernah', jumlah_pasangan_seksual: 4, penggunaan_kondom: 'Tidak', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Belum Kawin', usia_pertama_hubungan: 18, terapi_arv: 'Tidak', gejala_klinis: 'Gejala ringan', status_odhiv: 'ODHIV' },
  { nama: 'Pasien 07', umur: 27, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'ODHA', alasan_kunjungan: 'Konseling', riwayat_tes_hiv: 'Pernah (negatif)', riwayat_ims: 'Tidak ada', jumlah_pasangan_seksual: 2, penggunaan_kondom: 'Ya', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Belum Kawin', usia_pertama_hubungan: 21, terapi_arv: 'Tidak', gejala_klinis: 'Tidak ada gejala', status_odhiv: 'Bukan ODHIV' },
  { nama: 'Pasien 08', umur: 45, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'ODHA', alasan_kunjungan: 'Rujukan klinis', riwayat_tes_hiv: 'Pernah (positif)', riwayat_ims: 'Sedang terjadi', jumlah_pasangan_seksual: 3, penggunaan_kondom: 'Tidak', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Cerai', usia_pertama_hubungan: 19, terapi_arv: 'Ya', gejala_klinis: 'Gejala berat', status_odhiv: 'ODHIV' },
  { nama: 'Pasien 09', umur: 31, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'ODHA', alasan_kunjungan: 'IMS', riwayat_tes_hiv: 'Pernah (positif)', riwayat_ims: 'Pernah', jumlah_pasangan_seksual: 6, penggunaan_kondom: 'Tidak', penggunaan_napza_suntik: 'Ya', status_pernikahan: 'Belum Kawin', usia_pertama_hubungan: 16, terapi_arv: 'Ya', gejala_klinis: 'Gejala ringan', status_odhiv: 'ODHIV' },
  { nama: 'Pasien 10', umur: 26, jenis_kelamin: 'Perempuan', kelompok_populasi: 'Umum', alasan_kunjungan: 'Kontak serumah', riwayat_tes_hiv: 'Belum pernah', riwayat_ims: 'Tidak ada', jumlah_pasangan_seksual: 1, penggunaan_kondom: 'Ya', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Kawin', usia_pertama_hubungan: 23, terapi_arv: 'Tidak', gejala_klinis: 'Tidak ada gejala', status_odhiv: 'Bukan ODHIV' },
  { nama: 'Pasien 11', umur: 38, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'ODHA', alasan_kunjungan: 'Tes sukarela', riwayat_tes_hiv: 'Pernah (negatif)', riwayat_ims: 'Pernah', jumlah_pasangan_seksual: 4, penggunaan_kondom: 'Tidak', penggunaan_napza_suntik: 'Ya', status_pernikahan: 'Belum Kawin', usia_pertama_hubungan: 17, terapi_arv: 'Tidak', gejala_klinis: 'Gejala sedang', status_odhiv: 'ODHIV' },
  { nama: 'Pasien 12', umur: 29, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'Umum', alasan_kunjungan: 'Rujukan klinis', riwayat_tes_hiv: 'Belum pernah', riwayat_ims: 'Tidak ada', jumlah_pasangan_seksual: 2, penggunaan_kondom: 'Ya', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Kawin', usia_pertama_hubungan: 24, terapi_arv: 'Tidak', gejala_klinis: 'Tidak ada gejala', status_odhiv: 'Bukan ODHIV' },
  { nama: 'Pasien 13', umur: 24, jenis_kelamin: 'Perempuan', kelompok_populasi: 'Umum', alasan_kunjungan: 'Konseling', riwayat_tes_hiv: 'Belum pernah', riwayat_ims: 'Tidak ada', jumlah_pasangan_seksual: 1, penggunaan_kondom: 'Ya', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Belum Kawin', usia_pertama_hubungan: 21, terapi_arv: 'Tidak', gejala_klinis: 'Tidak ada gejala', status_odhiv: 'Bukan ODHIV' },
  { nama: 'Pasien 14', umur: 50, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'ODHA', alasan_kunjungan: 'IMS', riwayat_tes_hiv: 'Pernah (positif)', riwayat_ims: 'Sedang terjadi', jumlah_pasangan_seksual: 7, penggunaan_kondom: 'Tidak', penggunaan_napza_suntik: 'Ya', status_pernikahan: 'Cerai', usia_pertama_hubungan: 16, terapi_arv: 'Ya', gejala_klinis: 'Gejala berat', status_odhiv: 'ODHIV' },
  { nama: 'Pasien 15', umur: 32, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'ODHA', alasan_kunjungan: 'Konseling', riwayat_tes_hiv: 'Pernah (negatif)', riwayat_ims: 'Tidak ada', jumlah_pasangan_seksual: 2, penggunaan_kondom: 'Ya', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Belum Kawin', usia_pertama_hubungan: 20, terapi_arv: 'Tidak', gejala_klinis: 'Tidak ada gejala', status_odhiv: 'Bukan ODHIV' },
  { nama: 'Pasien 16', umur: 21, jenis_kelamin: 'Perempuan', kelompok_populasi: 'Umum', alasan_kunjungan: 'Ibu hamil', riwayat_tes_hiv: 'Belum pernah', riwayat_ims: 'Tidak ada', jumlah_pasangan_seksual: 1, penggunaan_kondom: 'Tidak', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Kawin', usia_pertama_hubungan: 19, terapi_arv: 'Tidak', gejala_klinis: 'Tidak ada gejala', status_odhiv: 'Belum Tahu' },
  { nama: 'Pasien 17', umur: 42, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'Waria', alasan_kunjungan: 'Kontak serumah', riwayat_tes_hiv: 'Pernah (positif)', riwayat_ims: 'Pernah', jumlah_pasangan_seksual: 5, penggunaan_kondom: 'Tidak', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Belum Kawin', usia_pertama_hubungan: 17, terapi_arv: 'Ya', gejala_klinis: 'Gejala sedang', status_odhiv: 'ODHIV' },
  { nama: 'Pasien 18', umur: 36, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'Umum', alasan_kunjungan: 'Rujukan klinis', riwayat_tes_hiv: 'Belum pernah', riwayat_ims: 'Tidak ada', jumlah_pasangan_seksual: 2, penggunaan_kondom: 'Ya', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Kawin', usia_pertama_hubungan: 23, terapi_arv: 'Tidak', gejala_klinis: 'Tidak ada gejala', status_odhiv: 'Bukan ODHIV' },
  { nama: 'Pasien 19', umur: 62, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'ODHA', alasan_kunjungan: 'Rujukan klinis', riwayat_tes_hiv: 'Pernah (positif)', riwayat_ims: 'Sedang terjadi', jumlah_pasangan_seksual: 2, penggunaan_kondom: 'Tidak', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Cerai', usia_pertama_hubungan: 20, terapi_arv: 'Ya', gejala_klinis: 'Gejala berat', status_odhiv: 'ODHIV' },
  { nama: 'Pasien 20', umur: 23, jenis_kelamin: 'Perempuan', kelompok_populasi: 'Umum', alasan_kunjungan: 'Tes sukarela', riwayat_tes_hiv: 'Belum pernah', riwayat_ims: 'Tidak ada', jumlah_pasangan_seksual: 1, penggunaan_kondom: 'Ya', penggunaan_napza_suntik: 'Tidak', status_pernikahan: 'Belum Kawin', usia_pertama_hubungan: 21, terapi_arv: 'Tidak', gejala_klinis: 'Tidak ada gejala', status_odhiv: 'Bukan ODHIV' },
  { nama: 'Pasien 21', umur: 34, jenis_kelamin: 'Laki-laki', kelompok_populasi: 'ODHA', alasan_kunjungan: 'IMS', riwayat_tes_hiv: 'Pernah (positif)', riwayat_ims: 'Pernah', jumlah_pasangan_seksual: 4, penggunaan_kondom: 'Tidak', penggunaan_napza_suntik: 'Ya', status_pernikahan: 'Belum Kawin', usia_pertama_hubungan: 18, terapi_arv: 'Ya', gejala_klinis: 'Gejala ringan', status_odhiv: 'ODHIV' },
];
